export const worktopImage = {
  worktop: require("./worktop.jpg"),
};

export const images = {
  oatmeal: require("./oatmeal.png"),
  oatmeal2: require("./oatmealPortion2.png"),
  oatmeal3: require("./oatmealPortion3.png"),
  yoghurt1: require("./yoghurt.png"),
  yoghurt2: require("./yoghurtPortion2.png"),
  yoghurt3: require("./yoghurtPortion3.png"),
  walnut1: require("./walnut.png"),
  walnut2: require("./walnutPortion2.png"),
  walnut3: require("./walnutPortion3.png"),
  riceMilk1: require("./riceMilk.png"),
  riceMilk2: require("./riceMilkPortion2.png"),
  riceMilk3: require("./riceMilkPortion3.png"),
  banana1: require("./banana.png"),
  banana2: require("./bananaPortion2.png"),
  banana3: require("./bananaPortion3.png"),
  grapes1: require("./grapes.png"),
  grapes2: require("./grapesPortion2.png"),
  grapes3: require("./grapesPortion3.png"),
  tangerine1: require("./tangerine.png"),
  // tangerine2: require("./tangerinePortion2.png"),
  // tangerine3: require("./tangerinePortion3.png"),
  dactyles: require("./dactyles.png"),
  // dactyles2: require("./dactylesPortion2.png"),
  // dactyles3: require("./dactylesPortion3.png"),
  blueberries1: require("./blueberries.png"),
  // blueberries2: require("./blueberriesPortion2.png"),
  // blueberries3: require("./blueberriesPortion3.png"),
  raspberries1: require("./raspberries.png"),
  // raspberries2: require("./raspberriesPortion2.png"),
  // raspberries3: require("./raspberriesPortion3.png"),
  watermelon1: require("./watermelon.png"),
  // watermelon2: require("./watermelonPortion2.png"),
  // watermelon3: require("./watermelonPortion3.png"),
  kiwi1: require("./kiwi.png"),
  // kiwi2: require("./kiwiPortion2.png"),
  // kiwi3: require("./kiwiPortion3.png"),
  blackberries1: require("./blackberries.png"),
  // blackberries2: require("./blackberriesPortion2.png"),
  // blackberries3: require("./blackberriesPortion3.png"),
  cranberries: require("./cranberries.png"),
  // cranberries2: require("./cranberriesPortion2.png"),
  // cranberries3: require("./cranberriesPortion3.png"),
};
