export const worktopImage = {
  worktop: require("./worktop.jpg"),
};

export const images = {
  oatmeal1: require("./oatmeal.png"),
  oatmeal2: require("./oatmealPortion2.png"),
  oatmeal3: require("./oatmealPortion3.png"),
  yoghurt1: require("./yoghurt.png"),
  yoghurt2: require("./yoghurtPortion2.png"),
  yoghurt3: require("./yoghurtPortion3.png"),
  walnut: require("./walnut.png"),
  walnutPortion2: require("./walnutPortion2.png"),
  walnutPortion3: require("./walnutPortion3.png"),
  riceMilk: require("./riceMilk.png"),
  riceMilkPortion2: require("./riceMilkPortion2.png"),
  riceMilkPortion3: require("./riceMilkPortion3.png"),
  banana: require("./banana.png"),
  bananaPortion2: require("./bananaPortion2.png"),
  bananaPortion3: require("./bananaPortion3.png"),
  grapes: require("./grapes.png"),
  grapesPortion2: require("./grapesPortion2.png"),
  grapesPortion3: require("./grapesPortion3.png"),
  tangerine: require("./tangerine.png"),
  dactyles: require("./dactyles.png"),
  blueberries: require("./blueberries.png"),
  raspberries: require("./raspberries.png"),
  watermelon: require("./watermelon.png"),
  kiwi: require("./kiwi.png"),
  blackberries: require("./blackberries.png"),
  cranberries: require("./cranberries.png"),
};
